### PR TITLE
UI Facelift

### LINKED ISSUE #82: Tournament page is messed up
Have not had time to investigate what is happening but lots of visible issues on our tournaments page following the testing session today:
- Modal doesn't close on tournament creation
- Obvious LiveView crash when deleting a tournament

Logs:

```
22:18:30.349 [info] CONNECTED TO LanpartyseatingWeb.DesktopClientSocket in 44µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
22:18:30.700 [info] JOINED desktop:all in 20µs
  Parameters: %{}
22:19:08.790 [info] CONNECTED TO LanpartyseatingWeb.DesktopClientSocket in 97µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
22:19:08.907 [info] JOINED desktop:all in 17µs
  Parameters: %{}
22:19:08.908 [info] JOINED desktop:all in 11µs
  Parameters: %{}
22:25:30.058 [info] CONNECTED TO Phoenix.LiveView.Socket in 46µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "Ojx5WSEzKyUTDVE0AFkBIl4CLiUgKUZAkN43YdAukagug7gusZLSoDw7", "_live_referer" => "http://172.16.2.7:4000/selfsign", "_mounts" => "0", "_track_static" => %{"0" => "http://172.16.2.7:4000/css/app-270c0beb8e8118a8236af5812e4a77e3.css?vsn=d", "1" => "http://172.16.2.7:4000/js/app-6ce61ce407d936fb99c5453f7d485fe5.js?vsn=d"}, "vsn" => "2.0.0"}
22:36:33.089 [info] GET /
22:36:33.089 [info] GET /
22:36:33.094 [info] Sent 200 in 5ms
22:36:33.094 [info] Sent 200 in 5ms
22:36:33.566 [info] CONNECTED TO Phoenix.LiveView.Socket in 27µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "J0UnKxdiWTwwKlozPjcnFEcPTzs4HnYlv7jAo53lHFlrYYACjW-MwsGR", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://172.16.2.7:4000/css/app-270c0beb8e8118a8236af5812e4a77e3.css?vsn=d", "1" => "http://172.16.2.7:4000/js/app-6ce61ce407d936fb99c5453f7d485fe5.js?vsn=d"}, "vsn" => "2.0.0"}
22:38:03.342 [info] GET /tournaments
22:38:03.343 [info] GET /tournaments
22:38:03.344 [info] Sent 200 in 1ms
22:38:03.344 [info] Sent 200 in 1ms
22:38:03.345 [info] CONNECTED TO Phoenix.LiveView.Socket in 37µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "J0UnKxdiWTwwKlozPjcnFEcPTzs4HnYlv7jAo53lHFlrYYACjW-MwsGR", "_live_referer" => "http://172.16.2.7:4000/selfsign", "_mounts" => "0", "_track_static" => %{"0" => "http://172.16.2.7:4000/css/app-270c0beb8e8118a8236af5812e4a77e3.css?vsn=d", "1" => "http://172.16.2.7:4000/js/app-6ce61ce407d936fb99c5453f7d485fe5.js?vsn=d"}, "vsn" => "2.0.0"}
22:38:03.738 [info] CONNECTED TO Phoenix.LiveView.Socket in 43µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "Nx40RxY4Ax1JXVEAMzEVA3ILPTQIXgIyfly-noiM11gAT_sT_S_BG33E", "_live_referer" => "undefined", "_mounts" => "0", "_track_static" => %{"0" => "http://172.16.2.7:4000/css/app-270c0beb8e8118a8236af5812e4a77e3.css?vsn=d", "1" => "http://172.16.2.7:4000/js/app-6ce61ce407d936fb99c5453f7d485fe5.js?vsn=d"}, "vsn" => "2.0.0"}
22:38:28.846 [error] GenServer #PID<0.2888.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:ok, [%{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 1, station_number: 1, display_order: 1, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:57], updated_at: ~N[2024-05-25 20:01:57]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 2, station_number: 2, display_order: 2, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 3, station_number: 3, display_order: 3, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 4, station_number: 4, display_order: 4, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 5, station_number: 5, display_order: 5, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 6, station_number: 6, display_order: 6, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 7, station_number: 7, display_order: 7, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 8, station_number: 8, display_order: 8, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 9, station_number: 9, display_order: 9, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 10, station_number: 10, display_order: 10, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 11, station_number: 11, display_order: 11, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 12, station_number: 12, display_order: 12, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 13, station_number: 13, display_order: 13, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 14, station_number: 14, display_order: 14, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 15, station_number: 15, display_order: 15, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 16, station_number: 16, display_order: 16, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 17, station_number: 17, display_order: 17, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 18, station_number: 18, display_order: 18, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 19, station_number: 19, display_order: 19, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 20, station_number: 20, display_order: 20, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 21, station_number: 21, display_order: 21, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 22, station_number: 22, display_order: 22, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 23, station_number: 23, display_order: 23, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 24, station_number: 24, display_order: 24, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :availa (truncated)
22:38:28.847 [error] GenServer #PID<0.2892.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:ok, [%{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 1, station_number: 1, display_order: 1, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:57], updated_at: ~N[2024-05-25 20:01:57]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 2, station_number: 2, display_order: 2, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 3, station_number: 3, display_order: 3, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 4, station_number: 4, display_order: 4, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 5, station_number: 5, display_order: 5, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 6, station_number: 6, display_order: 6, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 7, station_number: 7, display_order: 7, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 8, station_number: 8, display_order: 8, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 9, station_number: 9, display_order: 9, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 10, station_number: 10, display_order: 10, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 11, station_number: 11, display_order: 11, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 12, station_number: 12, display_order: 12, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 13, station_number: 13, display_order: 13, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 14, station_number: 14, display_order: 14, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 15, station_number: 15, display_order: 15, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 16, station_number: 16, display_order: 16, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 17, station_number: 17, display_order: 17, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 18, station_number: 18, display_order: 18, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 19, station_number: 19, display_order: 19, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 20, station_number: 20, display_order: 20, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 21, station_number: 21, display_order: 21, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 22, station_number: 22, display_order: 22, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 23, station_number: 23, display_order: 23, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 24, station_number: 24, display_order: 24, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :availa (truncated)
22:40:22.917 [info] CONNECTED TO LanpartyseatingWeb.DesktopClientSocket in 51µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
22:40:23.019 [info] JOINED desktop:all in 25µs
  Parameters: %{}
22:41:17.923 [error] GenServer #PID<0.3151.0> terminating
** (MatchError) no match of right hand side value: [:ok]
    (lanpartyseating 0.0.1) lib/lanpartyseating_web/live/tournaments_live.ex:23: LanpartyseatingWeb.TournamentsLive.handle_event/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F9Mq7bItvbPdU0AB", event: "event", payload: %{"event" => "delete_tournament", "type" => "form", "value" => "tournament_id=16"}, ref: "15", join_ref: "4"}
22:41:58.833 [info] CONNECTED TO LanpartyseatingWeb.DesktopClientSocket in 61µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}
22:41:58.852 [info] JOINED desktop:all in 24µs
  Parameters: %{}
22:41:58.853 [info] JOINED desktop:all in 33µs
  Parameters: %{}
22:41:59.374 [error] GenServer #PID<0.3157.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:ok, [%{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 1, station_number: 1, display_order: 1, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:57], updated_at: ~N[2024-05-25 20:01:57]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 2, station_number: 2, display_order: 2, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 3, station_number: 3, display_order: 3, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 4, station_number: 4, display_order: 4, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 5, station_number: 5, display_order: 5, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 6, station_number: 6, display_order: 6, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 7, station_number: 7, display_order: 7, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 8, station_number: 8, display_order: 8, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 9, station_number: 9, display_order: 9, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 10, station_number: 10, display_order: 10, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 11, station_number: 11, display_order: 11, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 12, station_number: 12, display_order: 12, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 13, station_number: 13, display_order: 13, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 14, station_number: 14, display_order: 14, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 15, station_number: 15, display_order: 15, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 16, station_number: 16, display_order: 16, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 17, station_number: 17, display_order: 17, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 18, station_number: 18, display_order: 18, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 19, station_number: 19, display_order: 19, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 20, station_number: 20, display_order: 20, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 21, station_number: 21, display_order: 21, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 22, station_number: 22, display_order: 22, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 23, station_number: 23, display_order: 23, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 24, station_number: 24, display_order: 24, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :availa (truncated)
22:41:59.374 [error] GenServer #PID<0.3161.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for {:ok, [%{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 1, station_number: 1, display_order: 1, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:57], updated_at: ~N[2024-05-25 20:01:57]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 2, station_number: 2, display_order: 2, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 3, station_number: 3, display_order: 3, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 4, station_number: 4, display_order: 4, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 5, station_number: 5, display_order: 5, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 6, station_number: 6, display_order: 6, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 7, station_number: 7, display_order: 7, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 8, station_number: 8, display_order: 8, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 9, station_number: 9, display_order: 9, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 10, station_number: 10, display_order: 10, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 11, station_number: 11, display_order: 11, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 12, station_number: 12, display_order: 12, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 13, station_number: 13, display_order: 13, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 14, station_number: 14, display_order: 14, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 15, station_number: 15, display_order: 15, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 16, station_number: 16, display_order: 16, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 17, station_number: 17, display_order: 17, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 18, station_number: 18, display_order: 18, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 19, station_number: 19, display_order: 19, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 20, station_number: 20, display_order: 20, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 21, station_number: 21, display_order: 21, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 22, station_number: 22, display_order: 22, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 23, station_number: 23, display_order: 23, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :available}, %{reservation: nil, station: %Lanpartyseating.Station{__meta__: #Ecto.Schema.Metadata<:loaded, "stations">, id: 24, station_number: 24, display_order: 24, is_closed: false, deleted_at: nil, reservations: [], tournament_reservations: [], inserted_at: ~N[2024-05-25 20:01:58], updated_at: ~N[2024-05-25 20:01:58]}, status: :availa (truncated)
22:42:37.813 [error] GenServer #PID<0.3176.0> terminating
** (MatchError) no match of right hand side value: [:ok]
    (lanpartyseating 0.0.1) lib/lanpartyseating_web/live/tournaments_live.ex:23: LanpartyseatingWeb.TournamentsLive.handle_event/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
    (telemetry 1.2.1) telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
    (stdlib 4.3.1.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.3) proc_lib.erl:250: :proc_lib.wake_up/3
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F9Mq7bItvbPdU0AB", event: "event", payload: %{"event" => "delete_tournament", "type" => "form", "value" => "tournament_id=17"}, ref: "21", join_ref: "16"}
```

### LINKED ISSUE #89: Change time display to minutes left instead of absolute time
It's just not useful and I didn't pay attention to the time almost at all this year

### LINKED ISSUE #95: Display physical table layout in the pages showing stations
The UI design needs to be thought out, but it would be great if we could group stations by table and have the station rectangles inside of big rectangles representing tables, that way it is more obvious to attendees how the floor plan on our app maps out the the real physical floor plan because it can be confusing at the moment depending on where the kiosk computer is placed, where projectors are showing the display page, etc.

### LINKED ISSUE #101: Add authentication
Gate admin pages behind login, possibly integrate with otakuthon account SSO.

### LINKED ISSUE #103: Add dynamic info on selfsign page
- When the LAN is full, in how many minutes will a PC be freed?
- Replace the end time with minutes till end countdown

### PR DESCRIPTION
**Pull request by starcraft66**
Tried to improve the general UI design of the app to make it have a bit more soul and not be some default CRUD with no theme. Added shadows, light animations, more graceful transitions between liveviews (eliminating FOUCs), generally giving things room to breathe.

Video explainer here: https://cornish-rex.s3.us-west-000.backblazeb2.com/Screen+Recording+2026-01-16+at+00.49.29.mov

Major new features:
- Added groups around the stations to simulate the IRL tables computers are sitting on
- Added authentication system with both local users and badge numbers
  - Leveraging Phoenix Authentication
      - Proper security (hashed passwords, resets, email support etc)
  - User accounts have more privileges than badges and can manage those
  - Initial user created in database seed
- Improved countdown displays, stations now count down until when they will become free instead of showing an absolute time
- Improved display of next available stations when event is full
- Improved navbar
  - Navbar is now responsive
  - Admin pages show up in nav bar if you're logged in
  - Login info shown in nav bar
- Adds a logs page showing the last 100 sessions (it's a start)
- Rename manhole to maintenance page

Major fixes:
- Restores tournament functionality

CI:
- Added workflow to automatically update the hash for the Mix deps FOD in the Nix package when `mix.exs` or `mix.lock` are updated

Closes #103 
Closes #101 
Closes #89 
Closes #82
Closes #95

### CODE REVIEW

**Review by babbaj — CHANGES_REQUESTED** [review]
image

The darker grey background bar should only be 1 button tall in this scenario.

I also noticed that the background bar can be vertical depending on gap settings which I appreciate and should be tested for when making the above change

File: priv/repo/migrations/20260115065330_create_users_auth_tables.exs [hunk 1]
```diff
@@ -0,0 +1,30 @@
+defmodule Lanpartyseating.Repo.Migrations.CreateUsersAuthTables do
+  use Ecto.Migration
+
+  def change do
+    execute "CREATE EXTENSION IF NOT EXISTS citext", ""
+
+    create table(:users) do
```
Comment (babbaj) [inline priv/repo/migrations/20260115065330_create_users_auth_tables.exs]: can we add a name column so we can identify who an account belongs to?

File: priv/repo/seeds.exs [hunk 2]
```diff
@@ -72,37 +72,79 @@
...
+#   is_banned: false,
+# })
+
+# Initial admin user (change password on first login!)
+# Email: admin@otakuthon.com
+# Password: change-me-on-first-login
+case Lanpartyseating.Accounts.get_user_by_email("admin@otakuthon.com") do
+  nil ->
+    Lanpartyseating.Accounts.create_user(%{
+      email: "admin@otakuthon.com",
```
Comment (babbaj) [inline priv/repo/seeds.exs]: please document this in the readme
